### ISSUE TITLE
lazygit

### ISSUE THREAD

**Issue by adrien-barret** [fnune/fnune.github.io#22]
Hi,

just saw your lunarvim reviw which was great ! But have one question, how do you found the lazygit ui? 
from luna last version they put in place a smaller gui which is not complete as needed.

ty,

Ad.

**Comment by fnune** [comment]
I still use Lazygit! Maybe I would only swap it out for Emacs + Magit. I'm thinking of doing that actually...

**Comment by adrien-barret** [comment]
I understand that so much ... I tried vim which I love due to terminal editing and fast launch but the management of the buffer is something I blame if I compare that to emacs.
I tried vscode and all the "auto" configuration like for dev in python, go, terraform.... and it have a magit like clone. At the final, it is so simple but no real buffer, no real magit, windows management is a pain... 
I considere to go back to emacs but lost my config. spacemacs and doom have too much bugs at least on osx that I need to make a new config.

But something I found is that making a custom config take longer time than all others solutions, and it make really slower emacs when you don't know how to optimize the config and the compilation

**Comment by fnune** [comment]
I used to have a Magit-only config for Emacs where basically I would:

- Launch Emacs in server mode
- Have a command that launches an Emacs client, then automatically launches Magit, then closes all other panes (leaving only Magit)

It worked great but I dropped it for some reason. I might get to writing that config again, it was pretty simple AFAIR.

**Comment by adrien-barret** [comment]
ho you would use emacs only for magit so

**Comment by fnune** [comment]
Yeah! I used to use Emacs for everything https://fnune.com/2017/12/27/making-emacs-work-like-my-vim-setup/

But now it's mostly Vim... and some PyCharm

**Comment by adrien-barret** [comment]
sounds good man, I'll look at that for sure ! 
what take you more on the vim side than emacs?

**Comment by fnune** [comment]
Not sure! I think it's just the fact that I'm trying to replicate how I use Vim in Emacs. I also stopped using Org Mode, so there was less of a reason to keep using Emacs.
